Green-Software-Foundation/carbon-aware-sdk

.github/workflows/build-cli-dotnet.yaml
.github/workflows/codeQL-analysis.yaml

hello, I have edited the previous pipeline to work with "feat/api-spec" updates.
some points to discuss later : dotnet versions supported and tests Plan 
the build action 
* uses version dotnet 6.0 
* runs a dummy regression test: ./bin/Debug/net6.0/CarbonAwareCLI -l eastus -d ./bin/Debug/net6.0/data-files/dummy-data-azure-emissions.json 
the CodeQL action: uses dotnet 6

Feat/api-spec : adding Action pipelines for build CI + CodeQL code Security Scan

---

README.md

Fixed link to license file

---

.github/workflows/build-cli-dotnet.yaml
src/CarbonAware.WebApi/test/unitTests/models/EmissionsDataDTOTests.cs

If yes, what workflow does this break? 
This PR Closes Issue #

Making comparison null forgiving as test will fail if null appropriately

---

src/CarbonAware.Aggregators/src/CarbonAware/CarbonAwareAggregator.cs
src/CarbonAware.Aggregators/test/CarbonAwareAggregatorTests.cs

Issue Number: [#83](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/83)
Updating the 'ByLocations' request to return comparable values when either start and/or end time is not provided. 
- Modified 'CarbonAware.Aggregators/src/CarbonAware/CarbonAwareAggregators'
- Changed the behavior of the 'GetEmissionsDataAsync' to be variable depending on the start and end props provided
- If 'end' prop is null and 'start' is provided, return the first value before the start time
- If 'start' is null and 'end' is provided, throw an error in accordance with the WattTime API
- If 'start' and 'end' are both null, return first value before the current time
- If neither are null, return the normal window of values.
No API changes
N/A
This PR Closes Issue #83

Limit responses when querying location endpoint

---

GettingStarted.md

Add description to build / run Web API on container to GetStarted.
Document changes only (GetStarted)
No
No

Add description to build / run Web API on container

---

docs/architecture/decisions/0004-documentation.md

ADR proposal for how to manage current and future documentation.

ADR 0004: Documentation

---

docs/architecture/decisions/0005-sdk-as-a-library.md
docs/architecture/decisions/0009-sdk-as-a-c#-client-library.md

Summary
Proposal for updating SDK to enable features for a C# client library
Changes
New ADR proposal
Anything else?
CC @vaughanknight @Willmish

SDK as a C# Library ADR

---

docs/architecture/decisions/0010-sdk-packaging.md

Proposal for Creating Nuget packages for CarbonAware SDK.
New ADR proposal
CC @vaughanknight @Willmish

Packaging CarbonAware SDK  ADR

---

docs/architecture/decisions/0007-data-source-interfaces.md

Proposal for improving data source interfaces.
- New ADR proposal
CC @vaughanknight @Willmish

Data Source Interfaces ADR

---

docs/architecture/decisions/0011-cd-pipeline.md

#46 
Proposal for CD pipeline for release process.
New ADR proposal

Add ADR-0011. CD pipeline for release process

---

src/CarbonAware.CLI/src/CarbonAware.CLI.csproj
src/CarbonAware.CLI/src/Commands/Emissions/EmissionsCommand.cs
src/CarbonAware.CLI/src/Commands/EmissionsForecasts/EmissionsForecastsCommand.cs
src/CarbonAware.CLI/src/Model/EmissionsDataDTO.cs
src/CarbonAware.CLI/src/Model/EmissionsForecastDTO.cs
src/CarbonAware.CLI/src/Program.cs
src/CarbonAware.CLI/test/integrationTests/CarbonAware.CLI.IntegrationTests.csproj
src/CarbonAware.CLI/test/integrationTests/Commands/Emissions/EmissionsCommandTests.cs
src/CarbonAware.CLI/test/integrationTests/Commands/EmissionsForecasts/EmissionsForecastsCommandTests.cs
src/CarbonAware.CLI/test/unitTests/CarbonAware.CLI.UnitTests.csproj
src/CarbonAware.CLI/test/unitTests/Commands/Emissions/EmissionsCommandTests.cs
src/CarbonAware.CLI/test/unitTests/Commands/EmissionsForecasts/EmissionsForecastsComandTests.cs
src/CarbonAware.CLI/test/unitTests/TestBase.cs

Issue Number: #269
**Warning** 
~~This PR depends on commits in other PRs> **DO NOT** merge this PR until https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/253 is merged and this branch is updated against the latest `dev` branch~~
NOTE - 253 Now approved
Migrate Carbon Aware CLI to consume CA library
- Updated CLI to use handlers, models, and exception in the GSF.CarbonAware Library
- Updated Unit Testing
- Updated Integration Testing
If yes, what are the expected API Changes? Please link to an API-Comparison workflow with the API Diff.
If yes, what workflow does this break? 
> Please follow [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-reque …

Migrate Carbon Aware CLI to consume CA library

---

samples/lib-integration/ConsoleApp/Program.cs
src/CarbonAware.CLI/src/Commands/EmissionsForecasts/EmissionsForecastsCommand.cs
src/CarbonAware.CLI/src/Model/EmissionsForecastDTO.cs
src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/src/ElectricityMapsDataSource.cs
src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/WattTimeDataSource.cs
src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/test/WattTimeDataSourceTests.cs
src/CarbonAware.WebApi/src/Controllers/CarbonAwareController.cs
src/CarbonAware.WebApi/src/Models/EmissionsForecastDTO.cs
src/CarbonAware.WebApi/test/unitTests/models/EmissionsForecastDTOTests.cs
src/CarbonAware/src/Model/EmissionsForecast.cs
src/GSF.CarbonAware/src/Handlers/ForecastHandler.cs
src/GSF.CarbonAware/src/Models/EmissionsForecast.cs
src/GSF.CarbonAware/test/ForecastHandlerTests.cs

Issue Number: #302 
Streamlined the model classes such that each consumer has its own DTO that is used for displaying user response.
- User specific input parameters are moved to Consumer model classes 
This PR Closes #302

Cleanup model classes

---

docs/overview.md

Fixing 3 broken links in overview.md
No
No
Nope

fixing 3 broken links in overview.md

---

docs/overview.md

Issue Number: N/A
Just fixed lost URL
- Update WattTime registration link

Update WattTime registration link

---

docs/enablement.md

Issue Number: #412 
add docs/enablement.md
add docs/enablement.md
No.
No.
This PR Closes #412

Draft of enablement.md

---

README.md

Issue Number: [(Link to Github Issue or Azure Dev Ops Task/Story)](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/460)
CarbonHack 24 banner added to readme
- CarbonHack 24 banner added to readme
This PR Closes #460

CarbonHack24 Update to README.md

---

README.md

Readme updated links to images
- Update links to both images on homepage
no
NO

Readme updated links to images

---

CONTRIBUTING.md

Contribution Documentation Updates for Graduation
Issue Number: #479
The contribution documentation needs to to include examples of areas of contribution opportunity to give a bit more clarity, just one sentence per item.  This PR updates that documentation (1 file)
- Updates to contribution.md
This update is for graduation

Contribution Documentation Updates for Graduation

---

CHANGELOG.md

Issue Number: [(Link to Github Issue or Azure Dev Ops Task/Story)
](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/503)
Changelog updates for release 1.4
-[#401] [Feature Contribution]: Upgrade .NET version to .NET 8 ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/401)
-[#419] [Feature Contribution]: Migrate sample implementation of Azure Function to isolated worker model ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/419)
-[PR #500] Up Helm chart version to 1.2.0 ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/500)
-[#397] [Feature Contribution]: Data caching in the SDK ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/397)
-[#505] [Bug]: Project Page wiki from GSF website still …

Release 1.4 changelog

---

CHANGELOG.md

Issue Number: [(Link to Github Issue or Azure Dev Ops Task/Story)](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/540)
Release notes for 1.5
This PR Closes #540

Update CHANGELOG.md for v1.5

---

CHANGELOG.md

updating changelog for 1.6.1
Issue Number: #579 
Updated changelog for 1.6.1
- changelog updated

Update CHANGELOG.md for 1.6.1

---

CHANGELOG.md

Issue Number: #601 
Changelog date correction for latest release
- changed date to jan 2025
This PR Closes #601

Changelog date correction for latest release
