- .devcontainer/devcontainer.json
- .vscode/launch.json
- .vscode/tasks.json
- src/dotnet/CarbonAware.WebApi/CarbonAware.WebApi.csproj
While upskilling on this repo, we made use of the following quick-tweaks locally:
1. Support of "F5-debugging" in VSCode with OmniSharp extension
2. Ensure the WebAPI Dockefile includes the data-files required by the Basic-Plugin
> Feat: Improve DevEx, and include data-files when publishing WebAPI 

- .github/workflows/build-webapi.yaml
This reverts commit 7c67ef125cc2efc584d967766af979552cc96df6.
This is to revert in place the api comparison in the dev branch for merge.  Due to folder structure changes this would fail on merge (by design) but stopped the first merge of this code.
Note - when merging to main this merge step will need to take place also thef irs ttime.
- API merge comparison put back in place
- [] Added any new Tests?
None.
No.
No.
> Revert "Temporary updates to the build yaml for comparison"

- src/CarbonAware.CLI/src/CarbonAwareCLI.cs
- src/CarbonAware.CLI/test/CarbonAwareCLITests.cs
Issue Number: #36 
Looking to fix the issue where the CLI returns an array instead of a JSON. Small fix, but first time contributing!
- Modify OutputEmissionsData#CarbonAwareCLI.cs to correct output
- Add a new test for doing a small verification of this logic (will likely want to expand out to proper tests + helpers etc in the future, but for now, wanting to kick off the review process!)
If yes, what are the expected API Changes? Please link to an API-Comparison workflow with the API Diff.
Yes - we're changing the format of how the CLI returns. I believe we're moving towards a more standardized JSON approach however.
If yes, what workflow does this break? 
Potentially breaking if workflows relied on just an array instead of JSON with array inside.
This …
> Fix: CLI returns a JSON with an array inside, instead of an array

- Dockerfile
I saw 2 errors when I attempted to build Docker container.  
Source files for CLI are located at `CarbonAware.CLI/src/`, however `src` does not specified in Dockerfile.
```
[1/2] STEP 4/13: RUN dotnet publish  ./CarbonAware.CLI/CarbonAware.CLI.csproj -c Release -o out --no-self-contained
MSBuild version 17.3.0+92e077650 for .NET
MSBUILD : error MSB1009: Project file does not exist.
```
```
[1/2] STEP 5/13: RUN cp ./CarbonAware.CLI/carbon-aware.json out
cp: cannot stat './CarbonAware.CLI/carbon-aware.json': No such file or directory
```
Added `src` to paths in some commands in Dockerfile.
No
No
> Incorrect paths for CLI is specified in Dockerfile

- src/CarbonAware.DataSources/CarbonAware.DataSources.Json/mock/CarbonAware.DataSources.Json.Mocks.csproj
- src/CarbonAware.DataSources/CarbonAware.DataSources.Json/mock/JsonDataSourceMocker.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.Mocks/mock/CarbonAware.DataSources.Mocks.csproj
- src/CarbonAware.DataSources/CarbonAware.DataSources.Mocks/mock/IDataSourceMocker.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/mock/CarbonAware.DataSources.WattTime.Mocks.csproj
- src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/mock/WattTimeDataSourceMocker.cs
- src/CarbonAware.Tools/CarbonAware.Tools.WattTimeClient/src/InternalsVisibleTo.cs
- src/CarbonAware.WebApi/test/integrationTests/CarbonAware.WebApi.IntegrationTests.csproj
- src/CarbonAware.WebApi/test/integrationTests/CarbonAwareControllerTests.cs
- src/CarbonAware.WebApi/test/integrationTests/IntegrationTestingBase.cs
- src/CarbonAwareSDK.sln
Issue Number: #122 
Refactor integration test mocks into new projects
- Move mocks into their own projects within `src/CarbonAware.DataSources/`
- `CarbonAware.DataSources.Mocks` for the shared interface
- `CarbonAware.DataSources.Json/mock` for the Json mocker
- `CarbonAware.DataSources.WattTime/mock` for the WattTime mocker
- Removed `OverrideWebAppFactory` from interface/implementations in favor of more consistent approach to configuration (using env vars) that also allows the interface to live outside the test suite.
- Visual Studio did some light cleanup around using directives
This PR Closes Issue #122
> Refactor integration test mocks into new projects

- GettingStarted.md
- src/CarbonAware.Tools/CarbonAware.Tools.WattTimeClient/src/Configuration/ServiceCollectionExtensions.cs
- src/CarbonAware.Tools/CarbonAware.Tools.WattTimeClient/src/Configuration/WattTimeClientConfiguration.cs
- src/CarbonAware.Tools/CarbonAware.Tools.WattTimeClient/src/WattTimeClient.cs
- src/CarbonAware.Tools/CarbonAware.Tools.WattTimeClient/test/WattTimeClientTests.cs
Issue Number: #124 
- Fetch data from WattTime service using streams instead of strings
- Cache in-memory a BalanceAuthority instance to avoid hitting WattTime service all the time for the same item.
- Improve retrieving the data when the header is available, then client can start to stream it, instead of waiting until all the content (string) is in available in memory.
- Change how WattTime Client reads content from the BA requests by leveraging the cache.
This PR Closes Issue #124
> Improve Reading Content from WattTime

- src/CarbonAware.DataSources/CarbonAware.DataSources.Json/src/JsonDataSource.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.Json/test/JsonDataSourceTests.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/test/WattTimeDataSourceTests.cs
- src/CarbonAware/src/IntervalHelper.cs
- src/CarbonAware/src/Model/Location.cs
- src/CarbonAware/test/IntervalHelperTests.cs
Issue Number: #155 
Fixes JSON DataSource bug
- Remove hardcoded default values for emissions data durations
- Update date filter to keep data points with ends that are `> start` filter time rather than `>= start` filter time.
CC: @pritipath @Willmish @vaughanknight 
This PR Closes Issue #155
> JSON data source bugfix

- docs/architecture/decisions/0005-IAsyncEnumerable-HttpResponseExceptionFilter.md
Issue Number: #126 
Capturing a relevant design decision within the webAPI to **NOT** use .NET streaming features
- ADR-0005 document that the proposal for using `IAsyncEnumerable` to stream at this time is **DENIED**
This PR Closes #126
> ADR-005 Using IAsyncEnumerable to stream large responses

- src/CarbonAware.DataSources/CarbonAware.DataSources.Json/mock/CarbonAware.DataSources.Json.Mocks.csproj
- src/CarbonAware.DataSources/CarbonAware.DataSources.Json/mock/JsonDataSourceMocker.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/WattTimeDataSource.cs
- src/CarbonAware.LocationSources/src/LocationSource.cs
Issue Number: #192 
When sending the geo location request with latitude and longitude the decimal is not forwarded to WattTime.
- Add `InvariantCulture` to location string ops
If yes, what are the expected API Changes? Please link to an API-Comparison workflow with the API Diff.
If yes, what workflow does this break? 
> Please follow [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link Pull Requests to Issues via keywords
This PR Closes #192
> [Bug Fix] Integration Tests + Location string need to be CultureInvariant

- .github/ISSUE_TEMPLATE/agenda-template.md
Issue Number: Outcome of the meeting: #248 
Added an Agenda Template for the weekly Carbon Aware SDK meetings. Example such issue can be found on my fork: https://github.com/Willmish/carbon-aware-sdk/issues/3
- Modifies the `.github/ISSUE_TEMPLATE` folder and adds a new `agenda-template.yml` file
None
N/A
> Please follow [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link Pull Requests to Issues via keywords
> Update issue templates

- src/CarbonAware.CLI/src/Commands/Location/LocalizableStrings.Designer.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/test/CarbonAware.DataSources.ElectricityMaps.Tests.csproj
- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/test/Client/ElectricityMapsClientTests.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/test/CarbonAware.DataSources.WattTime.Tests.csproj
- src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/test/Client/WattTimeClientTests.cs
Issue Number: #240 
Updating external client tests (ElectricityMapsClient and WattTimeClient) to use Moq infrastrucutre for HTTP requests
- Updated `ElectricityMapsClientTests.test.cs` and `WattTimeClientTests.test.cs` files to use Moq for Http client instead of custom class
This PR Closes #240
> Update clients to use Moq infrastrucutre for HTTP requests

- docs/configuration.md
- docs/overview.md
- docs/selecting-a-data-source.md
- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/src/Client/ElectricityMapsClient.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/src/Configuration/ElectricityMapsClientConfiguration.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/src/Constants/ErrorMessages.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/src/Constants/Headers.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/test/Client/ElectricityMapsClientTests.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/test/Configuration/ElectricityMapsClientConfigurationTests.cs
Issue Number: #266 
ElectricityMaps enforces many restrictions on users with a free trial token. This PR ensures those restrictions are properly documented for SDK users and more error prevention measures are in place to catch issues.
- Added documentation around restrictions
- Added more configuration validation to avoid invalid configurations between token/free trial users
- Added better error handling for failures free trial users may experience
This PR Closes #266
> Add docs + error checking to improve experience for free trial ElectricityMaps Users

- src/CarbonAware.CLI/test/integrationTests/IntegrationTestingBase.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/Client/WattTimeClient.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/Configuration/WattTimeClientConfiguration.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/test/Client/WattTimeClientTests.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/test/Configuration/WattTimeClientConfigurationTests.cs
- src/CarbonAware.WebApi/test/integrationTests/IntegrationTestingBase.cs
Issue Number: #181 
Fixed encoding bug that was causing WattTimeClient calls to fail when encoding non-ASCII characters in credentials.
- Moved to UTF8 encoding scheme
- Added configuration checks and test to ensure we catch the failure if it occurs again
This PR Closes #181
> Fixed encoding bug and added configuration test

- samples/pipeline/azure/gsf-package.yml
Issue Number: #268 
Add example on how to create GSF.CarbonAware package using AzDo pipeline.
- An example on how to build `GSF.CarbonAware` nuget package using Azure DevOps pipeline
This PR Closes #268, microsoft/carbon-aware-sdk#245
> AzDo pipeline sample for GSF.CarbonAware package

- src/CarbonAware.CLI/src/CarbonAware.CLI.csproj
- src/CarbonAware.CLI/src/Commands/Emissions/EmissionsCommand.cs
- src/CarbonAware.CLI/src/Commands/EmissionsForecasts/EmissionsForecastsCommand.cs
- src/CarbonAware.WebApi/src/Filters/CarbonAwareParametersBaseDtoOperationFilter.cs
- src/CarbonAware.WebApi/src/Filters/CarbonAwareParametersBaseDtoSchemaFilter.cs
- src/CarbonAware.WebApi/src/Models/Parameters.CarbonIntensityBatchDTO.cs
- src/CarbonAware.WebApi/src/Models/Parameters.CarbonIntensityDTO.cs
- src/CarbonAware.WebApi/src/Models/Parameters.EmissionsDataForLocationsDTO.cs
- src/CarbonAware.WebApi/src/Models/Parameters.EmissionsForecastBatchDTO.cs
- src/CarbonAware.WebApi/src/Models/Parameters.EmissionsForecastCurrentDTO.cs
- src/CarbonAware/src/CarbonAware.csproj
- src/CarbonAware/src/Model/CarbonAwareParameters.cs
- src/GSF.CarbonAware/src/Handlers/EmissionsHandler.cs
- src/GSF.CarbonAware/src/Handlers/ForecastHandler.cs
- src/GSF.CarbonAware/test/EmissionsHandlerTests.cs
- src/GSF.CarbonAware/test/LocationHandlerTests.cs
Issue Number: #284 
Move the `CarbonAwareParameters` class to the `CarbonAware` project
- Move class to CarbonAware project
- Update references
This PR Closes #284
> Move CarbonAwareParameters to CarbonAware Project

- src/CarbonAware.CLI/src/Commands/Location/LocationsCommand.cs
- src/CarbonAware.CLI/src/Extensions/CommandLineBuilderExtensions.cs
- src/CarbonAware.CLI/test/unitTests/Commands/Location/LocationCommandTests.cs
- src/CarbonAware.CLI/test/unitTests/TestBase.cs
- src/CarbonAware.WebApi/src/Filters/HttpResponseExceptionFilter.cs
- src/CarbonAware.WebApi/test/unitTests/HttpResponseExceptionFilterTests.cs
Issue Number: (#286)
After WebApi and CLI integration with GSF library (#245, #270) , relevant exceptions coming from providers were displayed as 500 internal error for the WebApi for instance. Root cause wasn't displayed.
This PR fixes this regression, bringing back the root cause of the error.
- Extract inner exception in case there is one as part of error handling done by the http/error handling filter class.
This PR Closes #286, microsoft/carbon-aware-sdk#256
> [Bug] 403 error is surfaced as 500 Internal

- samples/watttime-registration/3-makerequest.py
Issue Number: #281
Make the WattTime sample script always fetch data from last year.
- Instead of fetching data for a hard-coded date (2019-02-21), choose that day (21 February) of last year, where "last year" is calculated based on the current date. This should prevent the situation where the API doesn't return anything because the requested data are too old.
No
No
The [readme file](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/samples/watttime-registration/readme.md) reports an example of the output. Clearly, since now the date is calculated and changes every year, the output in the documentation cannot be byte-for-byte identical to the one that you really get (we'd have to update the documentation every year). But I don't think it's relevant.
This PR Closes …
> Make the WattTime sample script always fetch data from last year

- src/CarbonAware.CLI/test/unitTests/Commands/Emissions/EmissionsCommandTests.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/test/Client/WattTimeClientTests.cs
- src/CarbonAware.LocationSources/test/Model/NamedGeopositionTests.cs
Issue Number: #295
Unit tests must convert floats to strings in a culture-independent way
Fixed some tests in:
- src/CarbonAware.CLI/test/unitTests/Commands/Emissions/EmissionsCommandTests.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/test/Client/WattTimeClientTests.cs
- src/CarbonAware.LocationSources/test/Model/NamedGeopositionTests.cs
This PR Closes #295
> Unit tests must convert floats to strings in a culture-independent way

- src/CarbonAware.WebApi/src/Controllers/CarbonAwareController.cs
* Issue reference: #198
* Produces filters now accept application/json; charset=utf-8
Issue Number: #198 
Fix allows OpenAPI generated SDKs (namely - Python library) to accept responses from the API. It adds an annotation to the produced output from the CA API endpoints, so the generated libraries can consume them as well. See #198 how this failed before.
- Change annotations in WebAPI Controllers
> to link Pull …
> WebAPI: Bugfix: Add 'application/json; charset=utf-8' to Produces annotations.

- .github/workflows/build-webapi.yaml
Disabling API Comparison to allow completion of PR  https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/149
Issue Number: [(Link to Github Issue or Azure Dev Ops Task/Story)](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/149)
Disabling API Comparison to allow completion of PR  https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/149
- commented out api-comparison from related workflow
No
No
This PR relates to #29
> Disabling api-comparison to allow PR #149

- .github/workflows/stale.yml
Issues to be stale from 120 days of no activity
Label to change to stale and stale-pr to be more explicit
Issue Number: [(Link to Github Issue or Azure Dev Ops Task/Story)](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/318)
Shorten stale issues by 2 months and stale label to 'stale'
- Issues to be stale from 120 days of no activity
- Label to change to stale and stale-pr to be more explicit
No
No
This PR is related to [(Link to Github Issue or Azure Dev Ops …
> Shorten stale issues by 2 months and stale label to 'stale'

- .github/workflows/stale.yml
Updated Stale workflow to process more items.
We are trying to figure out the optimal value and what the job's stat signify so this may increase further.
> updated stale property of operations-per-run

- .github/workflows/2-pre-release.yaml
Proposal to use PowerShell rather than bash for package generation management.
Currently 2-pre-release.yaml uses bash to remove older container images because we need to keep recent 3 container images. GitHub Marketplace provides some useful actions for package management, but they are not track multi-arch container images. We need to manage both AMD64 and Arm64 container images. So we need to manage manually now.
I implemented it in bash in #327, but  it is a bit complex, so I'd like to propose to rewrite it in PowerShell. IMHO PowerShell is minor than bash, so I'm concerned the maintainer can maintain the workflow. Thus I'm not going to propose it strongly, but I think it is worth to discuss.
- `list-older-images` step in 2-pre-release.yaml
No
No
> [GitHub's suggested …
> Use PowerShell in 2-pre-release.yaml

- .github/workflows/2-pre-release.yaml
Fix workflow error in 2-pre-release.yaml.
Since #339 , we see workflow error due to unset GH_TOKEN. https://github.com/Green-Software-Foundation/carbon-aware-sdk/actions/runs/4923635734/jobs/8795681332  
So I added it to the workflow. It works fine on my forked repo: https://github.com/YaSuenag/carbon-aware-sdk/actions/runs/4924388705/jobs/8797365487
- 2-pre-release.yaml
No
No
> Fix workflow error in 2-pre-release.yaml

- docs/architecture/decisions/0014-dynamic-datasource-registration.md
Issue Number: (#289)
Add 0014 ADR for Dynamic Data Source Registration
- Document describing the proposal
N/A
N/A
This PR Closes #289, microsoft/carbon-aware-sdk#228
>  ADR Dynamic DataSource Registration

- src/CarbonAware.WebApi/src/Dockerfile
Install curl into WebAPI container for health check.
WebAPI provides endpoint for health check (/health), and we can use it for container health check (`--health-cmd` in `docker` / `podman`). However we cannot use any HTTP clients in WebAPI container because they are not installed.
According to [ASP.NET document](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-6.0#docker-healthcheck) which is base image of WebAPI container, it does not provides `curl`, but we can install it. We can see the result of health check in below after this change:
```json
"Healthcheck": {
"Status": "healthy",
"FailingStreak": 0,
"Log": [
{
"Start": "2023-05-27T12:28:38.1216648+09:00",
"End": "2023-05-27T12:28:38.2329616+09:00",
"ExitCode": 0,
"Output": ""
},
```
And …
> Install curl into WebAPI container

- .github/workflows/4-release.yaml
#252
Add 4-release.yaml to ship container image of the release.
This workflow would be triggered when the maintainer creates new release on GitHub release page. The container image has both `latest` and release version tag. Container image is for both AMD64 and Arm64, and they are pushlished to GitHub Packages.
You can see an example on my forked repo: https://github.com/YaSuenag/carbon-aware-sdk/pkgs/container/carbon-aware-sdk/88739206?tag=v99.0.23
- .github/workflows/4-release.yaml (new)
No
No
> Add 4-release.yaml to publish container image for the release

- .github/workflows/2-pre-release.yaml
- .github/workflows/dev_carbon-aware-api.yml
CASDK repo has two workflows for deployment.
* 2-pre-release.yaml - publish WebAPI container image to GitHub Packages
* dev_carbon-aware-api.yml - publish WebAPI to Azure Web Apps
They expect to run on original repo ( Green-Software-Foundation/carbon-aware-sdk ), however it would run on forked repo because they would also be triggered by pushing to `dev` branch. Thus we will see some errors on GHA as following.
* https://github.com/YaSuenag/carbon-aware-sdk/actions/runs/4862140346
* https://github.com/YaSuenag/carbon-aware-sdk/actions/runs/4862140351
It is noisy to work on forked repo, thus we need to skip them in forked repositories.
After this change, they are skipped as following:
* https://github.com/YaSuenag/carbon-aware-sdk/actions/runs/4890905942
* …
> Skip deploy workflows in forked repos

- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/src/ElectricityMapsDataSource.cs
Issue Number: #364
ElectricityMaps forecast scenario will return server error 500.
Repro using CLI:  "emissions-forecasts -l westeurope -v"
public async Task<EmissionsForecast> GetCurrentCarbonIntensityForecastAsync(Location location) is causing the EM server to return 500. Reason is that the "." in geolocation.Latitude will be passed as "," 
`public async Task<EmissionsForecast> GetCurrentCarbonIntensityForecastAsync(Location location)`
1) Fixing Input parameter validation for second condition to Longitude:
`if (geolocation.Latitude != null && geolocation.Longitude != null)`
2) Changing parameter parsing to use geolocation.LatitudeAsCultureInvariantString() and geolocation.LongitudeAsCultureInvariantString() to keep the correct formatting of the values. …
> Emissions-forecasts with ElectricityMaps will return server error 500

- docs/quickstart.md
Issue Number: #370 
Fixing args in commands shown in the quickstart.md document.
- `dotnet run` needs to be followed by a command such as emissions, locations, or emissions-forecasts
- `-t` is now `-s`
- `--toTime` is now `-e`
This PR Closes #370
> Fix CLI commands in quickstart.md 

- .github/workflows/verify-azure-function-with-packages.yaml
Issue Number: #383 
Replace current method of removing dangling images to do so only if there are any (and avoid running `docker rmi -f` with no params).
This PR Closes #383
> Fix: verify-azure-function-with-packages #383

- src/CarbonAware.CLI/test/integrationTests/Commands/Emissions/EmissionsCommandTests.cs
- src/CarbonAware.CLI/test/integrationTests/Commands/EmissionsForecasts/EmissionsForecastsCommandTests.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMapsFree/src/ElectricityMapsFreeDataSource.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMapsFree/test/ElectricityMapsFreeDataSourceTests.cs
Issue Number: N/A
Make ElectricityMapsFree data source aware of specifying time range. 
Currently WebAPI would return data even if it is out of time range which is specified in below:
```
Attempt to retrieve data to 2023-09-03T00:00:00Z from 2023-09-02T00:00:00Z
$ curl -s 'http://localhost:8082/emissions/bylocation?location=japaneast&startTime=2023-09-02T00%3A00%3A00Z&endTime=2023-09-03T00%3A00%3A00Z' | jq
[
{
"location": "japaneast",
"time": "2023-09-04T00:00:00+00:00",  <- out of range!
"rating": 530,
"duration": "00:00:00"
}
]
```
It should be returned empty (HTTP 204 or empty JSON array) or an error in this case.
- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMapsFree/src/ElectricityMapsFreeDataSource.cs
- Key point of this PR. [CO2Signal …
> EMFree data source should regard specified time range

- CHANGELOG.md
Issue Number: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/434
Updating the changelog for release [1.2](https://github.com/Green-Software-Foundation/carbon-aware-sdk/milestone/4)
- new changes and features
This PR Closes #434
> Update CHANGELOG.md for Release 1.2

- docs/overview.md
- helm-chart/Chart.yaml
- helm-chart/templates/configmap.yaml
- helm-chart/templates/deployment.yaml
- helm-chart/values.yaml
- src/CarbonAware.LocationSources/src/LocationSource.cs
Add location source configuration to Helm chart
- Add `locationSources` key to configure location source JSON.
- Ignore files which starts with `..` in `location-source` directory (Kubernetes sets real configuration file with `..`)
- Update documents for Helm
No
No
I want to update Helm chart version and to publish new chart container if this PR is accepted.
> Support location source setting in Helm chart

- CHANGELOG.md
Issue Number: [(Link to Github Issue or Azure Dev Ops Task/Story)](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/474)
Release 1.3 changelog
- Updated changelog for release 1.3
No
No
This PR Closes #474
> Release 1.3 changelog

- casdk-docs/docs/tutorial-extras/configuration.md
- src/CarbonAware.DataSources/CarbonAware.DataSources.Registration/Configuration/ServiceCollectionExtensions.cs
- src/CarbonAware/src/Configuration/EmissionsDataCacheConfiguration.cs
- src/CarbonAware/src/Configuration/EmissionsDataCacheConfigurationExtensions.cs
- src/CarbonAware/src/Proxies/Cache/LatestEmissionsCache.cs
- src/CarbonAware/test/CarbonAware.Tests.csproj
- src/CarbonAware/test/Configuration/EmissionsDataCacheConfigurationTests.cs
- src/CarbonAware/test/Proxy/Cache/LatestEmissionsCacheTests.cs
Issue Number: #397 
Add cache functionality for emissions data to avoid too frequent access to the data sources.
- Add a proxy for data sources to cache results for queries
- Add a configuration class to enable cache
- Modify service registration of data sources to use cache
- Write tests for verifying the configuration and  the functionality of the cache proxy
- Write document
No.
No.
This PR Closes #397
> Add cache functionality for emissions data

- casdk-docs/docs/tutorial-extras/configuration.md
- src/CarbonAware.WebApi/src/CarbonAware.WebApi.csproj
- src/CarbonAware.WebApi/src/Configuration/CarbonExporterConfiguration.cs
- src/CarbonAware.WebApi/src/Configuration/ServiceCollectionExtensions.cs
- src/CarbonAware.WebApi/src/Metrics/CarbonMetrics.cs
- src/CarbonAware.WebApi/src/Metrics/MetricsResourceDetector.cs
- src/CarbonAware.WebApi/src/Program.cs
- src/CarbonAware.WebApi/test/integrationTests/CarbonAwareControllerTests.cs
- src/CarbonAware.WebApi/test/integrationTests/IntegrationTestingBase.cs
- src/CarbonAware.WebApi/test/unitTests/Configuration/CarbonExporterConfigurationTests.cs
- src/CarbonAware.WebApi/test/unitTests/Configuration/ServiceCollectionExtensionsTests.cs
- src/CarbonAware/src/CarbonAwareVariablesConfiguration.cs
- src/GSF.CarbonAware/src/Configuration/ServiceCollectionExtensions.cs
Issue Number: #400
Add Prometheus exporter to CA SDK Web API. It exposes latest emission data for each configured location.
**This PR is based upon #404.**
- Add metrics to expose emission data
- Enable the endpoint for scraping by Prometheus
- Add configurations 
- Add tests
- Write documents
No.
No.
This PR Closes #400
> Add Prometheus exporter

- src/CarbonAware/src/Configuration/EmissionsDataCacheConfiguration.cs
This PR fixes regression that is occurred during rebasing accidentally in #421.
( The change at https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/421#discussion_r1501983386 have been lost. )
No.
No.
> Fix regression during rebase in #421

- .github/workflows/2-pre-release.yaml
- .github/workflows/4-release.yaml
- src/CarbonAware.WebApi/src/Dockerfile
- src/GSF.CarbonAware/src/GSF.CarbonAware.csproj
#496
Use RID to build WebAPI container.
- Use RID to build WebAPI container - QEMU is not supported in .NET https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/
- Fix version confliction in `System.IO.FileSystem.Primitives` https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605#example-3
- Separate OpenAPI document generation from `build-env` stage in WebAPI Dockerfile
You can test new container images from my forked repo. They works fine on both Linux x64 and Arm64 (Raspberry Pi) https://github.com/YaSuenag/carbon-aware-sdk/pkgs/container/carbon-aware-sdk/201841709?tag=v99.0.3
No
No
This PR Closes #496
> [URGENT] WebAPI container has not built due to segmentation fault

- helm-chart/Chart.yaml
Up Helm chart version to 1.2.0 because WebAPI would publish port 8080 due to .NET 8 migration since CASDK v1.4 . So I've also updated `appVersion` to v1.4.0.
> [!IMPORTANT]
> This should be merged after v1.4.0 release, then CASDK maintainer should be kick [5-publish-helm-chart.yaml](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/.github/workflows/5-publish-helm-chart.yaml) manually to publish new Helm chart to [charts/carbon-aware-sdk](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pkgs/container/charts%2Fcarbon-aware-sdk).
- helm-chart/Chart.yaml
No
No
> Up Helm chart version to 1.2.0

- SECURITY.md
- casdk-docs/docs/overview/enablement.md
Issue Number: #506 
updating .NET refecences older than 8
- also updated a broken link
- [NA ] Local Tests Passing?
- [ NA] CICD and Pipeline Tests Passing?
- [ NA] Added any new Tests?
- [ NA] Are there any API Changes? If yes, please describe below.
- [ NA] This is not a breaking change. If it is, please describe it below.
No
No
Thanks to Sophie for all the prep work...
This PR Closes #506
> Update published documentation to .NET 8

- casdk-docs/docusaurus.config.js
removed banner's mention of Hack
Issue Number: #519 
- removed the mention of the Carbon Hack 24
This PR Closes #519
> Remove Hack mention from the Docs's banner

- samples/casdk-demo/README.md
- samples/casdk-demo/casdk-config.yaml.template
- samples/casdk-demo/demo.sh
- samples/casdk-demo/demo.yaml
- samples/casdk-demo/nginx-rp.conf
I'd like to propose to add example for CASDK demonstration.
This example provides both the SDK and Swagger UI with just one command. Thus demonstrator does not need to prepare each components for WebAPI. I used this in [GSF Meetup Tokyo](https://github.com/Green-Software-Foundation/meetup/issues/49), then it works fine!
This example would use CASDK WebAPI container image tagged `pre` from GitHub Packages.
- samples/casdk-demo (new)
No
No
> Add example for 'podman play kube'

- src/data/location-sources/azure-regions.json
Latest azure-regions.json list 
Adds italynorth, polandcentral, spaincentral, mexicocentral, israelcentral, qatarcentral, brazilus, eastusstg (Also seems to remove trailing zeros in some existing coordinates)
Updated list of azure regions. It adds italynorth, polandcentral, spaincentral, mexicocentral, israelcentral, qatarcentral, brazilus, eastusstg
- Updated list of azure regions using `az account list-locations --query '[?metadata.latitude != null].{Name:name,Longitude:metadata.longitude,Latitude:metadata.latitude}' | jq 'reduce .[] as $item ({}; .[$item.Name] = $item)' > azure-regions.json`
If yes, what workflow does …
> Updated azure-regions.json with new regions

- casdk-docs/docs/tutorial-extras/configuration.md
- src/CarbonAware.DataSources/CarbonAware.DataSources.Json/mock/JsonDataSourceMocker.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.Json/src/Configuration/JsonDataSourceConfiguration.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.Json/src/JsonDataSource.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.Json/test/CarbonAware.DataSources.Json.Tests.csproj
- src/CarbonAware.DataSources/CarbonAware.DataSources.Json/test/JsonDataSourceTests.cs
Support dynamic update for emission data JSON file.
It is useful if we can update emission data when we use custom data via JSON datasource.
Currently JSON datasource would cache all of data in JSON on memory, so the update would not propagate even if it is updated. We have to restart WebAPI when we need to update emission data. It is not good for system operation.
I want to introduce `CacheJsonData` into JSON datasource configuration. If the user set it to `false`, JSON datasource would read emission data JSON file everytime when the request happens. This option is set to `true` by default, so this PR does not break current behavior.
- JSON datasource
- Test case for above
- Document for JSON datasource
No
No
> Add a configuration for disabling to cache JSON emission data

- casdk-docs/docs/overview/enablement.md
- casdk-docs/docs/troubleshooting.md
- helm-chart/Chart.yaml
- helm-chart/templates/deployment.yaml
- helm-chart/values.yaml
#528 
Add troubleshooting document to avoid `System.IO.IOException` caused by number of inotify instances on Linux, and add `env` directive to `values.yaml` in Helm chart. See #528 for details.
- CASDK document
- `values.yaml` in Helm chart
No
No
This PR Closes #528
> Add env directive to values.yaml and troubleshooting guide to avoid inotify limitation on Linux

- src/CarbonAware.WebApi/src/Controllers/CarbonAwareController.cs
> Update CarbonAwareController.cs (minor typos)

- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/src/Model/HistoryCarbonIntensityData.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/test/Client/ElectricityMapsClientTests.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/test/Client/TestData.cs
Issue Number: #571 
Consider null value(s) if it is returned from Electricity Maps.
This PR set `-1` to `HistoryCarbonIntensityData.Vaule` when `carbonIntensity` in response body from Electricity Maps is `null`. But I'm not sure it is ok because `-1` does not mean `null` - it might be ok it is documented. Or we can exclude it in filter phase in data source implementation. What do you think?
- HistoryCarbonIntensityData.cs
No
No
This PR Closes #571
> Consider null value in carbonIntensity on EM

- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/src/ElectricityMapsDataSource.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/test/ElectricityMapsDataSourceTests.cs
Issue Number: #570 
bylocation query in EM datasource did not reagard with specified time range. See #570 for more details.
- EM Datasource and testcase
No
Yes, SDK user would not see any out-of-range emission data, but it is correct behavior.
This PR Closes #570
> EM datasource didn't filter out-of-range emission data

- casdk-docs/docs/tutorial-extras/configuration.md
- src/CarbonAware.WebApi/src/Configuration/ServiceCollectionExtensions.cs
- src/CarbonAware.WebApi/src/Program.cs
- src/CarbonAware.WebApi/test/unitTests/Configuration/ServiceCollectionExtensionsTests.cs
- src/CarbonAware/src/CarbonAwareVariablesConfiguration.cs
Introduce new configuration `EnableTelemetryLogging` into `CarbonAwareVars`. This configures whether console exporter by OpenTelemetry is enabled. If you set this to `false`, following log would be gone:
```
Activity.TraceId:            46ba0749bdd2381c8f8aded1986e74b2
Activity.SpanId:             bcb76b5718c7df35
Activity.TraceFlags:         Recorded
Activity.ActivitySourceName: Microsoft.AspNetCore
Activity.DisplayName:        /health
Activity.Kind:               Server
Activity.StartTime:          2024-06-12T10:36:51.3093434Z
Activity.Duration:           00:00:00.0221267
Activity.Tags:
net.host.name: localhost
net.host.port: 8080
http.method: GET
http.scheme: http
http.target: /health
http.url: http://localhost:8080/health
http.flavor: 1.1
http.user_agent: curl/8.5.0
http.status_code: …
```
> Add configuration for tracing log

- .devcontainer/devcontainer.json
quick one to add the github cli to codespaces for this repository
- Updated devcontainer.json to list github cli as a feature
> Add gh cli to devcontainer/codespace

- CHANGELOG.md
- casdk-docs/blog/2024-11-30-relese1.6.1.mdx
- casdk-docs/blog/2025-01-07-release-1.7.mdx
Issue Number: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/601
This PR Closes #601
> Update CHANGELOG.md for 1.7

- casdk-docs/docs/tutorial-basics/carbon-aware-webapi.md
- casdk-docs/docs/tutorial-extras/carbon-aware-library.md
- src/CarbonAware.WebApi/src/Controllers/CarbonAwareController.cs
- src/CarbonAware.WebApi/src/Models/CarbonIntensityDTO.cs
- src/GSF.CarbonAware/src/Handlers/IForecastHandler.cs
Issue Number: [Link to Github Issue or Azure Dev Ops Task/Story)](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/612)
Make the documentation for forecasts, signal agnostic.
- In the carbon aware sdk documentation, remove the mention of marginal as if you use ElectricityMaps' signals, the signals you will get are not marginal forecasts but average carbon intensity. To avoid any confusion, making the documentation signal agnostic.
- Update the carbon aware API documentation accordingly.
No, only documentation changes.
> [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linkin …
> Make documentation for forecasts signal agnostic

- src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/Client/WattTimeClient.cs
- src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/test/Client/WattTimeClientTests.cs
@vaughanknight @danuw Please review this PR. I think it is urgent bug.
`co2_moer` and `co2_aoer` have been supported since #611 , however WattTime client is possibility not to work after this change.
#611 introduces these values as `enum`, not `stiring. It might cause deserialization error.
```
fail: CarbonAware.WebApi.Filters.HttpResponseExceptionFilter[0]
Exception: The JSON value could not be converted to CarbonAware.DataSources.WattTime.Constants.SignalTypes. Path: $.signal_type | LineNumber: 0 | BytePositionInLine: 102.
System.Text.Json.JsonException: The JSON value could not be converted to CarbonAware.DataSources.WattTime.Constants.SignalTypes. Path: $.signal_type | LineNumber: 0 | BytePositionInLine: 102.
at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
at …
```
> [URGENT] Set JsonStringConverter to JSON deserializer option in WattTimeClient
